logging:
  level:
    org.springframework: ERROR

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  main:
    banner-mode: off

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=imageDetection
    username: jackson
    password: jackson
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl