logging:
  level:
    org.springframework: ERROR

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  main:
    banner-mode: off

  datasource:
    url: jdbc:sqlserver://localhost;databaseName=imageDetection
    username: username
    password: password